### ISSUE TITLE
Flagd gRPC object deserialization is not working properly

### ISSUE THREAD

**Issue by beeme1mr** [open-feature/node-sdk-contrib#101]
Objects returned by flagd are not deserialized as expected:

http:
```
{
  "key": "val"
}
```

grpc
```
{
  "fields": {
    "key": {
      "kind": {
        "oneofKind": "stringValue",
        "stringValue": "val"
      }
    }
  }
}
```

**Comment by beeme1mr** [comment]
FYI, @james-milligan

**Comment by toddbaert** [comment]
I'll take this one, just a little missing parsing, but I'm going to add some tests.

**Comment by toddbaert** [comment]
I'm also using this chance to remove HTTP support from the provider as we discussed.
