### ISSUE TITLE
Remove Context Transformer from Go Feature Flag

### ISSUE THREAD

**Issue by beeme1mr** [open-feature/node-sdk-contrib#91]
An upcoming change to the OpenFeature node SDK will remove the context transformer. The Go Feature Flag provider currently uses the context transforming and will be affected by this change. You can see an example of how the provider could look in [this PR](https://github.com/open-feature/playground/pull/53/files#diff-cd559fb92aa816531c3c94ea4724f0b40917e27fb0a627e71c9f3e9521acf4b4).

**Comment by thomaspoignant** [comment]
I am on PTO for the next 2 weeks.
Is it fine if I am doing it when I am back ?

**Comment by beeme1mr** [comment]
Okay, no problem. Todd or I will take care of it. Enjoy your vacation!
